variables:
  BUILD_IMAGE: docker:stable

image: ${BUILD_IMAGE}

stages:
  - build

img:branch:snapshot:
  stage: build
  tags:
    - docker-builder
  only:
    - branches
  script:
    # Build an image
    - export VERSION_TAG_CURRENT="${CI_COMMIT_REF_SLUG}.${CI_COMMIT_SHORT_SHA}"
    - export VERSION_TAG_LATEST="${CI_COMMIT_REF_SLUG}"
    - docker build ${DOCKER_ARGS} --file Dockerfile
      --tag "image-${CI_JOB_ID}"
      .
    # Login to the registry
    - echo "${CI_REGISTRY_PASSWORD}" | docker login --username "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"
    # Make image tags
    - export DOCKER_IMAGE_NAME="${CI_REGISTRY_IMAGE}/snapshot"
    # Tag
    - docker tag "image-${CI_JOB_ID}" "${DOCKER_IMAGE_NAME}:${VERSION_TAG_CURRENT}"
    - docker tag "image-${CI_JOB_ID}" "${DOCKER_IMAGE_NAME}:${VERSION_TAG_LATEST}"
    # Publish tags
    - docker push "${DOCKER_IMAGE_NAME}:${VERSION_TAG_CURRENT}"
    - docker push "${DOCKER_IMAGE_NAME}:${VERSION_TAG_LATEST}"
    - echo "See README.md for 'docker run' command. The image ${DOCKER_IMAGE_NAME}:${VERSION_TAG_CURRENT}"
    - echo "See README.md for 'docker run' command. The image ${DOCKER_IMAGE_NAME}:${VERSION_TAG_LATEST}"
