ARG BUILD_IMAGE=alpine:3.19.1

FROM ${BUILD_IMAGE} AS postgres_builder
ARG POSTGRES_PACKAGE_VERSION=13.15-r0
RUN apk add --no-cache postgresql13=${POSTGRES_PACKAGE_VERSION} postgresql13-contrib=${POSTGRES_PACKAGE_VERSION}
COPY docker/docker-builder.sh     /build/usr/local/bin/docker-builder-postgres-13.sh
COPY docker/docker-healthcheck.sh /build/usr/local/bin/docker-healthcheck-postgres-13.sh
COPY docker/docker-entrypoint.sh  /build/usr/local/bin/docker-entrypoint-postgres-13.sh
COPY docker/init-data/            /.builder-postgres.d/
RUN /build/usr/local/bin/docker-builder-postgres-13.sh


FROM ${BUILD_IMAGE}
ARG POSTGRES_PACKAGE_VERSION=13.15-r0
RUN apk add --no-cache postgresql13=${POSTGRES_PACKAGE_VERSION} postgresql13-contrib=${POSTGRES_PACKAGE_VERSION}
COPY --from=postgres_builder /build/ /
USER root
#HEALTHCHECK --interval=15s --timeout=5s  --start-period=2s --start-interval=1s --retries=6    CMD /usr/local/bin/docker-healthcheck-postgres-13.sh
HEALTHCHECK  --interval=1s  --timeout=10s --start-period=300s                   --retries=128  CMD /usr/local/bin/docker-healthcheck-postgres-13.sh
#
# Volume /data make more problems than benefits...
# For some case we want to embed data in /data, but this is not possible due volume directive.
#
# https://stackoverflow.com/questions/44020785/remove-a-volume-in-a-dockerfile
# https://stackoverflow.com/questions/40006278/prevent-volume-creation-on-docker-run
#
# Comment it temporary while 
#VOLUME /data
EXPOSE 5432
ENTRYPOINT ["/usr/local/bin/docker-entrypoint-postgres-13.sh"]
